apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://stakater.github.io/stakater-charts'
    targetRevision: v1.0.50
    chart: reloader
    helm:
      values: |-
        reloader:
          deployment:
            image:
              name: ghcr.io/stakater/reloader
              tag: v1.0.50
        ignoreSecrets: false
  destination:
    server: test-two-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2