apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-components
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/PatrickLaabs/cluster-1.git'
    path: registry/test-two-cluster/components/guestbook
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false