apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-components
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: git@github.com:eitco/appsOfapps.git
    path: registry/test-one-cluster/components/guestbook
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false