apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: git@github.com:eitco/appsOfapps.git
    path: registry/jenkins-prod-cluster/components/argocd-image-updater
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
